version: '3'
services:
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.insecure=false
      - --providers.docker
      - --accesslog=true
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --certificatesresolvers.leresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.leresolver.acme.email=nargathron@gmail.com
      - --certificatesresolvers.leresolver.acme.storage=/acme.json
      - --certificatesresolvers.leresolver.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/tgbot/certs/:/acme.json
  tgbot:
    image: "nargathron/tgbot-pomoja:latest"
    container_name: "tgbot"
    labels:
      - "traefik.http.routers.adminer.rule=Host(`vpn.borgyy.gq`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=80"
      - "traefik.http.routers.adminer.entrypoints=websecure"
      - "traefik.http.routers.adminer.tls.certresolver=leresolver"
    volumes:
      - /root/tgbot/.env:/usr/src/app/.env
