name: Dockerize TgBot application
on: push
jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push to Docker Hub Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: nargathron/tg-bot:latest

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -p9022 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy new images
        run: docker-compose pull && docker-compose up -d
